name: crypto
version: 3.0.2
description: Implementations of SHA, MD5, and HMAC cryptographic functions
repository: https://github.com/dart-lang/crypto

environment:
  sdk: '>=2.14.0 <5.0.0'

dependencies:
  typed_data: ^1.3.0

dev_dependencies:
  convert: any
  lints: any
  test: ^1.22.1 