name: pbkdf2_dart
version: 2.1.0
author: James Ots <code@jamesots.com>
homepage: https://github.com/marceloneppel/pbkdf2
description: Implementation of PBKDF2 key derivation function
environment:
  # Works in Dart 1 (starting with 1.20.1), and works in Dart 2.
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  crypto1:
    path: './crypto1-3.0.2'
dev_dependencies:
  # test: ^1.22.1 
