name: rethinkdb_dart
publish_to: none
version: 2.3.2+6
description: Dart 2 driver for RethinkDB v2.3.
homepage: https://github.com/marceloneppel/rethinkdb
documentation: https://github.com/marceloneppel/rethinkdb
environment:
  sdk: ">=2.3.0 <3.1.0"
dependency_overrides:
  meta: 1.6.0 # https://github.com/dart-lang/sdk/issues/46687#issuecomment-890541823
dependencies:
  protobuf:
    path: './protobuf-0.13.16+1'
  crypto:
    path: './pbkdf2_dart-2.1.0/crypto-3.0.2'
  convert: 
    path: './convert-2.1.1'
  pbkdf2_dart:
    path: './pbkdf2_dart-2.1.0'
dev_dependencies:
  # test: any
  pedantic: ^1.8.0
