name: protobuf
version: 0.13.16+1
publish_to: none
description: >
  Runtime library for protocol buffers support.
  Use https://pub.dartlang.org/packages/protoc_plugin to generate dart code for your '.proto' files.
homepage: https://github.com/dart-lang/protobuf

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  fixnum1:
    path: './fixnum1-0.10.11'

dev_dependencies:
  test: '>=1.2.0'
  benchmark_harness: any
  js: any
