name: fixnum
version: 0.10.11

description: Library for 32- and 64-bit signed fixed-width integers.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/fixnum

environment:
  sdk: '>=2.12.1 <4.1.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.2.0
