name: mockito
version: 4.1.4

description: A mock framework inspired by Mockito.
homepage: https://github.com/dart-lang/mockito

environment:
  sdk: '>=2.7.0 <4.0.0'

dependencies:
  analyzer: any
  build: any
  code_builder: any
  collection: ^1.1.0
  dart_style: any
  http: any
  matcher: ^0.12.3
  meta: ^1.3.0-nullsafety
  source_gen: any
  test_api: any

dev_dependencies:
  # build_runner: ^1.0.0
  # build_test: ^1.1.0
  # build_web_compilers: '>=1.0.0 <3.0.0'
  # package_config: ^1.9.3
  pedantic: ^1.10.0-nullsafety
  test: ^1.5.1
