name: encrypt
version: 5.0.1
description: A set of high-level APIs over PointyCastle for two-way cryptography.
homepage: https://github.com/leocavalcante/encrypt

executables:
  secure-random:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.0.0
  asn1lib: ^1.0.0
  clock: ^1.1.0
  collection: ^1.15.0
  crypto1:
    path: '../rethinkdb/pbkdf2_dart-2.1.0/crypto1-3.0.2'
  pointycastle: 
    path: '../rethinkdb/pointycastle-3.5.0'

dev_dependencies:
  test: ^1.16.8
